### ISSUE TITLE
How to get output for devices_by_attr, models_by_name, etc

### ISSUE THREAD

**Issue by kharder69** [orgito/spectrum-client#1]
I have the following python script and getting no output when I know there is a model with that IP and Name, the maintenance mode function works.
from spectrum_client import Spectrum

oc = Spectrum('http://x.x.x.x', 'userid', 'password')

# Put a model in maintenance mode
oc.set_maintenance(0x220e2e, True)

# Update notes attribute
notes = 'in maintenance mode'
updates = [(0x11564, notes)]
oc.update_attributes(0x220e2e, updates)

# Get list of devices by name
oc.models_by_name('.*MRKINW.*', 0x200000)

# Get devices by specific attribute
oc.devices_by_attr(0x12d7f, '10.1.1.32')

**Comment by orgito** [comment]
The methods will return a dictionary containing the matching models. The model handle as the key for each object.

The second argument in `models_by_name` and `devices_by_name` is the landscape handle. Is  0x200000 the right landscape handle? You can omit it to search in all landscapes:
`oc.devices_by_name('MRKINW')`

`oc.devices_by_attr(0x12d7f, '10.1.1.32')` will search only devices and only the Network_Address attribute (the one used to register the device in Spectrum). It will not search for secondary IPs or models.
